#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/wxprec.h>

//// end generated include
#include "General.h"
#include <numeric>
#include <algorithm>
#include <mutex>
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.

	//opens dialog window warning about losing all changes
	void Frame_OnCLose(wxCloseEvent& event);

	//void OriginalImage_OnUpdateUI(wxUpdateUIEvent& event);

	//validates input
	void ValueText_OnTextEnter(wxCommandEvent& event);

	void ApplyChanges_OnButtonClick(wxCommandEvent& event);

	void ResultImage_OnUpdateUI(wxUpdateUIEvent& event);
	void OriginalImage_OnUpdateUI(wxUpdateUIEvent& event);

	//loads file (via dialog window)
	void LoadFile(wxCommandEvent& event);

	//saves ready file (via dialog window)
	void SaveFile(wxCommandEvent& event);

	//opens dialog window showing project info
	void AboutProject(wxCommandEvent& event);

public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members
private:
	void useGaussian2WithThreads(wxImage& img, int width, int height, int howManyThreads);

private:
	wxImage originalPhoto, copyPhoto; //Zmienne na zdjêcia
	int tresholdParameter = 0; //Próg desaturacji
	int blurParameter = 0; //Zmienna przechowuj¹ca rozmiar obszaru przejœciowego
	int saturationParameter = 0; //Procent saturacji
	int selectedOption = 0; //Zmienna przechowuj¹ca wybran¹ opcjê
	bool should_refresh = false; //zmienna typu logicznego, okreœla czy za³adowano zdjêcie i trzeba wywo³ywaæ funkcjê odœwie¿aj¹ce
	std::mutex mutex; //mutex zapobiega równoczesnemu dostêpowi w¹tków do tablicy

protected:
	void value_check(); //funkcja sprawdzaj¹ca czy wartoœæ pola value mieœci siê w zadanym przedziale i reaguj¹ca odpowiednie na b³êdne wejœcie
	void firstRefresh(wxClientDC &dc); //Odœwie¿anie panelu orgina³u
	void secondRefresh(wxClientDC &dc); //Odœwia¿anie panelu kopii
	void useGaussian2(int start_width, int end_width, int width, int height, unsigned char* org, unsigned char* copy); //U¿ycie Gaussa 5x5
	void modifyImage(); //Modyfikacja obrazu
};

#endif // __GUIMyFrame1__
